#!/bin/fish

alias sc='systemctl'
alias sc-status='sc status'
alias sc-show='sc show'
alias sc-enable='sc enable'
alias sc-disable='sc disable'
alias sc-start='sc start'
alias sc-stop='sc stop'
alias sc-restart='sc restart'
alias shutdown='sc poweroff'
alias hibernate='sc hibernate'
alias suspend='sc suspend'
