#!/bin/bash

# Dot files path
DOTFILESPATH=~/DotFiles/files

# Where it gets saved
HISTFILE=~/.history

# Remember about a years worth of history (AWESOME)
SAVEHIST=100000
HISTSIZE=100000

# Don't overwrite, append!
setopt APPEND_HISTORY

# Write after each command
# setopt INC_APPEND_HISTORY

# Killer: share history between multiple shells
setopt SHARE_HISTORY

# If I type cd and then cd again, only save the last one
setopt HIST_IGNORE_DUPS

# Even if there are commands inbetween commands that are the same, still only save the last one
setopt HIST_IGNORE_ALL_DUPS

# Pretty    Obvious.  Right?
setopt HIST_REDUCE_BLANKS

# If a line starts with a space, don't save it.
setopt HIST_IGNORE_SPACE
setopt HIST_NO_STORE

# When using a hist thing, make a newline show the change before executing it.
setopt HIST_VERIFY

# Save the time and HIST_SAVE_NO_DUPSow long a command ran
setopt EXTENDED_HISTORY

setopt HIST_SAVE_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt no_complete_aliases

# Default editor
export EDITOR="vim"

# Keys
bindkey '^[[1;5C' emacs-forward-word
bindkey '^[[1;5D' emacs-backward-word
bindkey '^[[1;2D' beginning-of-line
bindkey '^[[1;2C' end-of-line

# Aliases
for f in ${DOTFILESPATH}/aliases/*; do
   source $f
done

# For any extra non committed bashrc bits
if [ -f ~/.bashrc.local ]; then
    source ~/.bashrc.local
fi