#!/bin/bash

# Oh My ZSH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"
skip_global_compinit=1

source $ZSH/oh-my-zsh.sh

# Bashrc
source ~/.bashrc

# For any extra non committed zshrc bits
if [ -f ~/.zshrc.local ]; then
    source ~/.zshrc.local
fi